global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter-1:9308']

  - job_name: 'kafka-brokers'
    static_configs:
      - targets: ['broker-1:19092', 'broker-2:29092', 'broker-3:39092']